frontend/lib/screens/bottom_navigation_bar.dart, frontend/lib/screens/camera/camera_screen.dart, frontend/lib/screens/camera/gallery_screen.dart, frontend/lib/screens/record/record_screen.dart, frontend/pubspec.yaml
=> FE/feat : 체형 갤러리 퍼블리싱 디벨롭 반영

frontend/lib/screens/bottom_navigation_bar.dart, frontend/lib/screens/exercise/exercise_screen.dart, frontend/pubspec.yaml
=> Fe/feat : 운동 선택 스크린 퍼블리싱

frontend/lib/screens/bottom_navigation_bar.dart, frontend/lib/screens/calendar/calendar_screen.dart, frontend/lib/screens/camera/body_scan.dart, frontend/lib/screens/camera/camera_screen.dart, frontend/lib/screens/exercise/exercise_camera.dart, frontend/lib/screens/exercise/exercise_screen.dart, frontend/lib/screens/exercise/hip.dart, frontend/lib/screens/exercise/leg.dart, frontend/lib/screens/exercise/neck.dart, frontend/lib/screens/exercise/waist.dart, frontend/lib/screens/login/login_screen.dart, frontend/lib/screens/login/sign_up_modal.dart, frontend/lib/screens/record/record_screen.dart
=> Fe/feat : 운동 설명 페이지 초기 틀 및 카메라 연결

docker-compose.yml, frontend/lib/screens/login/login_screen.dart, frontend/lib/screens/login/mypage_modal.dart, frontend/lib/screens/login/sign_up_modal.dart, frontend/lib/services/api_client.dart, frontend/pubspec.yaml
=> FE/feat: 유저 페이지 연동

backend/health/routes.py
*한 줄 설명*
헤더에 access token 삽입 후 요청
- health/routes - access token을 가져오는 부분 추가
=>  BE/refactor: 헤더에 access token 삽입 후 요청

backend/exercise/mediapipe/front.py, backend/exercise/mediapipe/side.py
=> feat: 정면, 측면 각도 계산

frontend/lib/screens/record/record_screen.dart
=> feat: 그래프 조회 api 앱 연동

backend/health/crud.py, backend/health/routes.py
사용자가 새로운 사진 찍을 시 새로운 행 추가 
- health/routes, crud
=> refactor: 사용자가 새로운 사진 찍을 시 새로운 행 추가 

backend/health/crud.py, backend/health/routes.py
query문 수정 - order by 추가
- health routes, crud
*실행 결과 스크린샷*
=> refactor: query문 수정 - order by 추가

backend/health/crud.py, backend/health/routes.py, backend/health/schemas.py, backend/models.py, frontend/lib/screens/camera/gallery_screen.dart
=> refactor: createdAt 시간 오류 수정 및 갤러리 리스트 변환

frontend/lib/screens/camera/body_scan.dart, frontend/lib/screens/camera/camera_screen.dart, frontend/lib/screens/camera/gallery_screen.dart, frontend/lib/screens/record/record_screen.dart, frontend/lib/services/api_client.dart
=> refactor : 카메라 측정 페이지 타이머 시간 연장 및 글씨 색상 변경

backend/exercise/routes.py, backend/main.py, backend/models.py, backend/session/crud.py, backend/session/routes.py, backend/session/schemas.py, frontend/lib/screens/calendar/calendar_screen.dart, frontend/lib/screens/camera/body_scan.dart, frontend/lib/screens/camera/camera_screen.dart, frontend/lib/screens/camera/gallery_screen.dart, frontend/lib/screens/exercise/exercise_camera.dart, frontend/lib/screens/record/record_screen.dart, frontend/lib/services/api_client.dart
=> feat : 캘린더 api 구현 및 프론트 연동

backend/exercise/routes.py
=> feat: 최신운동파일로 변경

frontend/lib/screens/calendar/calendar_screen.dart, frontend/lib/screens/camera/body_scan.dart, frontend/lib/screens/camera/camera_screen.dart, frontend/lib/screens/camera/gallery_screen.dart, frontend/lib/screens/exercise/exercise_camera.dart, frontend/lib/screens/record/record_screen.dart, frontend/lib/services/api_client.dart
=> feat: ip 주소 변경

backend/exercise/mediapipe/exercise/leg.py, backend/exercise/mediapipe/exercise/neck.py, backend/exercise/mediapipe/exercise/squat.py, backend/exercise/mediapipe/exercise/waist.py, backend/exercise/routes.py, frontend/lib/screens/exercise/exercise_camera.dart
=> feat : 가중치 적용 및 운동 횟수 5회로 수정

docker-compose.yml, nginx/nginx.conf
=> feat: nginx 설정 완료

backend/exercise/routes.py, frontend/android/app/build.gradle, frontend/android/build.gradle
=> feat: 하드웨어 카운트 데이터 수집

backend/database.py, backend/exercise/mediapipe/exercise/leg.py, backend/exercise/mediapipe/exercise/neck.py, backend/exercise/routes.py, backend/main.py, frontend/lib/screens/calendar/calendar_screen.dart, frontend/lib/screens/camera/body_scan.dart, frontend/lib/screens/camera/camera_screen.dart, frontend/lib/screens/camera/gallery_screen.dart, frontend/lib/screens/exercise/exercise_camera.dart, frontend/lib/screens/exercise/exercise_screen.dart, frontend/lib/screens/grade/grade_screen.dart, frontend/lib/screens/record/record_screen.dart, frontend/lib/services/api_client.dart
=> feat : 점수 계산 로직 수정

backend/exercise/routes.py, frontend/lib/screens/exercise/exercise_camera.dart
=> feat: 운동 세트 1회로 수정

backend/exercise/routes.py, frontend/lib/screens/exercise/exercise_camera.dart
=> feat : 운동 로직 수정

backend/exercise/routes.py, backend/requirements.txt, frontend/lib/screens/bottom_navigation_bar.dart
=> feat : 3세트로 수정
